version: '3.1'

services:
  server:
    build:
      context: ./server
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - DATABASE_URL=mongodb://root:admin@localhost:27017/
      - JWT_SECRET=odkfokoskf
      - PORT=8080
    network_mode: host

  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL=140.238.181.171
      - REACT_APP_SERVER_PORT=8080
      - REACT_APP_GATEWAY_PORT=8081
      - REACT_APP_HTTPS=false
    network_mode: host

  mongo:
    image: mongo
    restart: always
    network_mode: host
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - database:/data/db

volumes:
  database:
