services:
  server:
    build:
      context: ./server
    environment:
      DATABASE_URL: mongodb://root:admin@mongo:27017/
      JWT_SECRET: odkfokoskf
      PORT: 8080

  client:
    build:
      context: ./client
      args:
        REACT_APP_SERVER_URL: "localhost:80/api"
        REACT_APP_GATEWAY_URL: "localhost:80/gateway"
        REACT_APP_HTTPS: true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - database:/data/db

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  database:
